#pragma once

#include <QtCore/qglobal.h>

#if defined(IISOCIETYCONTAINER_BUILDING_LIBRARY)
#  define IISOCIETYCONTAINER_EXPORT Q_DECL_EXPORT
#else
#  define IISOCIETYCONTAINER_EXPORT Q_DECL_IMPORT
#endif
