include_guard(GLOBAL)

function(iiSocietyContainer_configure_android_client target)
    if(NOT ANDROID)
        message(FATAL_ERROR "Society Android clients require an Android Qt build")
    endif()
    set(package "${CMAKE_CURRENT_BINARY_DIR}/android-society-client/${target}")
    file(MAKE_DIRECTORY "${package}/src/com/iisacc/society/storage")
    get_target_property(existing ${target} QT_ANDROID_PACKAGE_SOURCE_DIR)
    if(existing AND EXISTS "${existing}/AndroidManifest.xml")
        file(COPY "${existing}/" DESTINATION "${package}")
        set(manifest "${existing}/AndroidManifest.xml")
    else()
        get_filename_component(qt_prefix "${Qt6_DIR}/../../.." ABSOLUTE)
        set(manifest "${qt_prefix}/src/android/templates/AndroidManifest.xml")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
    file(READ "${manifest}" xml)
    string(REPLACE "</manifest>" "<uses-permission android:name=\"com.iisacc.society.permission.STORAGE\" /></manifest>" xml "${xml}")
    if(xml MATCHES "</queries>")
        string(REPLACE "</queries>" "<provider android:authorities=\"com.iisacc.society.internal\" /></queries>" xml "${xml}")
    else()
        string(REPLACE "</manifest>" "<queries><provider android:authorities=\"com.iisacc.society.internal\" /></queries></manifest>" xml "${xml}")
    endif()
    file(WRITE "${package}/AndroidManifest.xml" "${xml}")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/com/iisacc/society/storage/SocietyClient.java"
        "${package}/src/com/iisacc/society/storage/SocietyClient.java" COPYONLY)
    set_target_properties(${target} PROPERTIES QT_ANDROID_PACKAGE_SOURCE_DIR "${package}")
endfunction()

# Society is the single Android owner. Client apps must use URI grants; installing
# a second provider under the same authority would conflict with the owner app.
function(iiSocietyContainer_add_android_file_provider target)
    if(NOT ANDROID)
        message(FATAL_ERROR "The Android Society provider requires an Android Qt build")
    endif()
    set(package "${CMAKE_CURRENT_BINARY_DIR}/android-society/${target}")
    file(MAKE_DIRECTORY "${package}/assets/society")
    file(GLOB_RECURSE sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/*.java")
    foreach(source IN LISTS sources)
        file(RELATIVE_PATH relative "${CMAKE_CURRENT_FUNCTION_LIST_DIR}" "${source}")
        configure_file("${source}" "${package}/${relative}" COPYONLY)
    endforeach()
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../apple/Sections.json" "${package}/assets/society/Sections.json" COPYONLY)
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/AndroidManifest.xml" "${package}/AndroidManifest.xml" COPYONLY)
    set_target_properties(${target} PROPERTIES QT_ANDROID_PACKAGE_SOURCE_DIR "${package}"
        QT_ANDROID_PACKAGE_NAME "com.iisacc.society" QT_ANDROID_MIN_SDK_VERSION 28 QT_ANDROID_TARGET_SDK_VERSION 35)
endfunction()
